parameters:
#    propeller_user.example.class: Propeller\Bundle\UserBundle\Example

services:
#    propeller_user.example:
#        class: %propeller_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
